---
version: '3'
services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: zaninime/baikal:php-0.4.6-2
    networks:
      - infra
    volumes:
      - db_data:/var/lib/baikal
    environment:
      BAIKAL_ADMIN_PASSWORD: admin
      BAIKAL_AUTH_REALM: BaikalDAV
      BAIKAL_CAL_ENABLED: 'true'
      BAIKAL_CARD_ENABLED: 'true'
      BAIKAL_ENCRYPTION_KEY: 683a736f6592c2ed4d4fe9c15732967b
      PROJECT_TIMEZONE: Europe/Berlin
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: zaninime/baikal:nginx-0.4.6-2
    ports:
      - 32770:80
    depends_on:
      - php
    networks:
      - infra
      - frontend

networks:
  infra:
    internal: true
  frontend:

volumes:
  db_data:
