---
version: '3'
services:
  unifi:
    image: zaninime/unifi:5.8.28-1
    ports:
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 3478:3478/udp
    volumes:
      - data:/data
    environment:
      JVM_OPTS: '-d64 -XX:+UseG1GC -Xms256m -Xmx256m -XX:MaxGCPauseMillis=500 -XX:+PrintGCTimeStamps'
volumes:
  data:
