version: '2.4'
services:
  app:
    image: zaninime/unifi-controller:6.4.54
    volumes:
      - ./unifi/data:/unifi/data
      - ./unifi/log:/unifi/log
      - ./unifi/run:/unifi/run
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - db
    environment:
      INITIAL_SYSTEM_PROPERTIES: |
        db.mongo.local=false
        db.mongo.uri=mongodb\://db\:27017/unifi
        statdb.mongo.uri=mongodb\://db\:27017/unifi-stats
        unifi.db.name=unifi
        # debug.system=debug
        # debug.mgmt=debug
  db:
    image: mongo:4.2.0
    volumes:
      - ./mongo/db:/data/db
